### ISSUE TITLE
Problems when using the fallback mode from rails-i18n

### ISSUE THREAD

**Issue by philipp-spiess** [fnando/i18n-js#334]
I have set up the fallback mode from the `i18n` gem described here: https://github.com/svenfuchs/i18n/wiki/Fallbacks

In my `production.rb`:

```ruby
require "i18n/backend/fallbacks" 
I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
```

Now I can no longer run `rake assets:precompile` (or run the Middleware on development) because it's giving me the following exception:

```
  NoMethodError: undefined method `merge' for nil:NilClass

  i18n/js/utils.rb:18:in `deep_merge'
    target_hash.merge(hash, &MERGER)
  i18n/js.rb:68:in `block (2 levels) in merge_with_fallbacks!'
    result[locale] = Utils.deep_merge(result[fallback_locale], result[locale] || {})
  i18n/js/fallback_locales.rb:12:in `block in each'
    locales.each { |locale| yield(locale) }
  i18n/js/fallback_locales.rb:12:in `each'
    locales.each { |locale| yield(locale) }
  i18n/js/fallback_locales.rb:12:in `each'
    locales.each { |locale| yield(locale) }
  i18n/js.rb:67:in `block in merge_with_fallbacks!'
    fallback_locales.each do |fallback_locale|
  i18n/js.rb:65:in `each'
    I18n.available_locales.each do |locale|
  i18n/js.rb:65:in `merge_with_fallbacks!'
    I18n.available_locales.each do |locale|
  i18n/js.rb:55:in `block in configured_segments'
    merge_with_fallbacks!(result) if fallbacks
  i18n/js.rb:46:in `each'
    config[:translations].inject([]) do |segments, options|
  i18n/js.rb:46:in `inject'
    config[:translations].inject([]) do |segments, options|
  i18n/js.rb:46:in `configured_segments'
    config[:translations].inject([]) do |segments, options|
  i18n/js.rb:85:in `translation_segments'
    configured_segments
  i18n/js.rb:75:in `block in filtered_translations'
    translation_segments.each do |segment|
  i18n/js.rb:74:in `tap'
    translations = {}.tap do |result|
  i18n/js.rb:74:in `filtered_translations'
    translations = {}.tap do |result|
  javascripts/i18n/filtered.js.erb:17:in `block in singleton class'
    I18n.translations = <%= I18n::JS.filtered_translations.to_json %>;
  tilt/template.rb:170:in `call'
    method.bind(scope).call(locals, &block)
  tilt/template.rb:170:in `evaluate'
    method.bind(scope).call(locals, &block)
  tilt/template.rb:103:in `render'
    evaluate scope, locals || {}, &block
  sprockets/context.rb:197:in `block in evaluate'
    result = template.render(self, {})
  sprockets/context.rb:194:in `each'
    processors.each do |processor|
  sprockets/context.rb:194:in `evaluate'
    processors.each do |processor|
  sprockets/processed_asset.rb:12:in `initialize'
    @source = context.evaluate(pathname)
  sprockets/base.rb:374:in `new'
    ProcessedAsset.new(index, logical_path, pathname)
  sprockets/base.rb:374:in `block in build_asset'
    ProcessedAsset.new(index, logical_path, pathname)
  sprockets/base.rb:395:in `circular_call_protection'
    yield
  sprockets/base.rb:373:in `build_asset'
    circular_call_protection(pathname.to_s) do
  sprockets/index.rb:94:in `block in build_asset'
    super
  sprockets/caching.rb:58:in `cache_asset'
    elsif asset = yield
  sprockets/index.rb:93:in `build_asset'
    cache_asset(key) do
  sprockets/base.rb:287:in `find_asset'
    build_asset(logical_path, pathname, options)
  sprockets/index.rb:61:in `find_asset'
    elsif asset = super
  sprockets/processed_asset.rb:44:in `block in init_with'
    p == pathname.to_s ? self : environment.find_asset(p, :bundle => false)
  sprockets/processed_asset.rb:37:in `map'
    @required_assets = coder['required_paths'].map { |p|
  sprockets/processed_asset.rb:37:in `init_with'
    @required_assets = coder['required_paths'].map { |p|
  sprockets/asset.rb:24:in `from_hash'
    asset.init_with(environment, hash)
  sprockets/caching.rb:54:in `cache_asset'
    elsif (asset = Asset.from_hash(self, cache_get_hash(path.to_s))) && asset.fresh?(self)
  sprockets/index.rb:93:in `build_asset'
    cache_asset(key) do
  sprockets/base.rb:287:in `find_asset'
    build_asset(logical_path, pathname, options)
  sprockets/index.rb:61:in `find_asset'
    elsif asset = super
  sprockets/bundled_asset.rb:37:in `init_with'
    @processed_asset = environment.find_asset(pathname, :bundle => false)
  sprockets/asset.rb:24:in `from_hash'
    asset.init_with(environment, hash)
  sprockets/caching.rb:54:in `cache_asset'
    elsif (asset = Asset.from_hash(self, cache_get_hash(path.to_s))) && asset.fresh?(self)
  sprockets/index.rb:93:in `build_asset'
    cache_asset(key) do
  sprockets/base.rb:287:in `find_asset'
    build_asset(logical_path, pathname, options)
  sprockets/index.rb:61:in `find_asset'
    elsif asset = super
  sprockets/manifest.rb:211:in `block in find_asset'
    asset = environment.find_asset(logical_path)
  sprockets/manifest.rb:257:in `benchmark'
    yield
  sprockets/manifest.rb:210:in `find_asset'
    ms = benchmark do
  sprockets/manifest.rb:119:in `block in compile'
    if asset = find_asset(path)
  sprockets/manifest.rb:118:in `each'
    paths.each do |path|
  sprockets/manifest.rb:118:in `compile'
    paths.each do |path|
  sprockets/rails/task.rb:70:in `block (3 levels) in define'
    manifest.compile(assets)
  rake/sprocketstask.rb:146:in `with_logger'
    yield
  sprockets/rails/task.rb:69:in `block (2 levels) in define'
    with_logger do
  rake/task.rb:240:in `call'
    act.call(self, args)
  rake/task.rb:240:in `block in execute'
    act.call(self, args)
  rake/task.rb:235:in `each'
    @actions.each do |act|
  rake/task.rb:235:in `execute'
    @actions.each do |act|
  rake/task.rb:179:in `block in invoke_with_call_chain'
    execute(task_args) if needed?
  monitor.rb:211:in `mon_synchronize'
    yield
  rake/task.rb:172:in `invoke_with_call_chain'
    @lock.synchronize do
  rake/task.rb:165:in `invoke'
    invoke_with_call_chain(task_args, InvocationChain::EMPTY)
  rake/application.rb:150:in `invoke_task'
    t.invoke(*args)
  rake/application.rb:106:in `block (2 levels) in top_level'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:106:in `each'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:106:in `block in top_level'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:115:in `run_with_threads'
    yield
  rake/application.rb:100:in `top_level'
    run_with_threads do
  rake/application.rb:78:in `block in run'
    top_level
  rake/application.rb:176:in `standard_exception_handling'
    yield
  rake/application.rb:75:in `run'
    standard_exception_handling do
  ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    Rake.application.run
  vendor/bundle/bin/rake:16:in `load'
    load Gem.bin_path('rake', 'rake')
  vendor/bundle/bin/rake:16:in `<main>'
    load Gem.bin_path('rake', 'rake')
``` 

I'm having the following versions up and running:

```
i18n (0.7.0)
i18n-js (3.0.0.rc10)
      i18n (~> 0.6)
rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails
````

Edit:
Apparently it's not good to have fallbacks enabled on two different areas. I've disabled `i18n-js` fallback in the configuration file using `fallbacks: false` and it's working now (although it's no longer providing me fallbacks).

**Comment by PikachuEXE** [comment]
Thanks for reporting first of all.
It's helpful that you have provided your dependency and backtrace, but I am unable find the error class or message from your provided info.
I think it would be easy to be fixed once the error class & message is given.

**Comment by philipp-spiess** [comment]
I'm so sorry. I've updated the original description. Looks like `target_hash` is nil :)

**Comment by PikachuEXE** [comment]
Please use `master` to see if issue fixed

**Comment by PikachuEXE** [comment]
Hello?

**Comment by romanbsd** [comment]
Had the same problem, master fixed this.

**Comment by philipp-spiess** [comment]
Thank you for your quick fix @PikachuEXE, I have verified and it indeed fixed the problem for me :+1:

**Comment by PikachuEXE** [comment]
I will release another version on Friday
Since the #326 takes much longer to finish...
