### ISSUE TITLE
NoMethodError: undefined method `register_preprocessor' for nil:NilClass

### ISSUE THREAD

**Issue by dt1973** [fnando/i18n-js#381]
Using Rails 4.2.4:
```
% bundle exec rake assets:precompile RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `register_preprocessor' for nil:NilClass
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/i18n-js-2.1.2/lib/i18n-js/engine.rb:12:in `block in <class:Engine>'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
/usr/home/www/myapp/config/environment.rb:5:in `<top (required)>'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/www/myapp/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by dt1973** [comment]
This is most likely due to Sprockets, a temp fix would be to set this in your Gemfile:

```
gem 'sprockets-rails', '~> 2'
```

**Comment by PikachuEXE** [comment]
Please try `master` and see if it fixes the problem
I will release it once enough people confirmed it's working fine

**Comment by Deckluhm** [comment]
It works fine for me while using `master`.

Maybe you should let this issue open if you want more people to give you feedbacks.

**Comment by PikachuEXE** [comment]
Sure :)

**Comment by PikachuEXE** [comment]
I will properly release this before the new year anyway

**Comment by PikachuEXE** [comment]
`3.0.0.rc12` released with fix for this issue
