### ISSUE TITLE
Rails 4.2.4: uninitialized constant ApplicationController::SimplesIdeias

### ISSUE THREAD

**Issue by dt1973** [fnando/i18n-js#388]
Hello!

Using the latest i18n-js (`gem "i18n-js", github: "fnando/i18n-js"`) I seem to be getting:
```
% rake i18n:js:setup --trace
rake aborted!
Don't know how to build task 'i18n:js:setup' (see --tasks)
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/task_manager.rb:62:in `[]'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:149:in `invoke_task'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.2/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

Using Ruby 2.2.0p0.

**Comment by PikachuEXE** [comment]
That task only exists in older versions
`master` represents `3.0.0.rc*` now

**Comment by dt1973** [comment]
Thanks -- I guess that settles it!
