### ISSUE TITLE
Problem using this with React-Native 0.57

### ISSUE THREAD

**Issue by ItsNoHax** [fnando/i18n-js#527]
I was running into the following problem.

```
error: bundling failed: Error: While trying to resolve module `i18n-js` from file `/home/alberto/Programming/Workspace/app-react-native-2/src/lib/i18n.js`, the package `/home/alberto/Programming/Workspace/app-react-native-2/node_modules/i18n-js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/alberto/Programming/Workspace/app-react-native-2/node_modules/i18n-js/app/assets/javascripts/i18n.js`. Indeed, none of these files exist:

  * `/home/alberto/Programming/Workspace/app-react-native-2/node_modules/i18n-js/app/assets/javascripts/i18n.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/home/alberto/Programming/Workspace/app-react-native-2/node_modules/i18n-js/app/assets/javascripts/i18n.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:61:15)
    at DependencyGraph.resolveDependency (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
    at /home/alberto/Programming/Workspace/app-react-native-2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:309:15
```

Your package was working correct when using React-Native versions 56 and lower but I believe they made some changes in Metro (the react-native bundler) that avoids JS files in any /assets/ folder.
Made an issue in their repository: https://github.com/facebook/metro/issues/326

Is there any reason you put the JS files under /assets/?

**Comment by azhararmar** [comment]
I had issues with installing on RN 0.57, it is working for me when I use manual linking.
