### ISSUE TITLE
Bug: i18n-js is not compatible with Vite

### ISSUE THREAD

**Issue by mkhalifa013** [fnando/i18n-js#723]
## Description

When trying to build or run with Vite bundler the i18n doesn't work and fails with the following error:

```RollupError: "I18n" is not exported by "node_modules/i18n-js/dist/browser/index.js", imported by "src/locales/index.js".
file: /Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/src/locales/index.js:3:9
1: // import { I18n } from "i18n-js";
2: console.log("TESTTTT");
3: import { I18n } from "i18n-js";
            ^
4: 
5: console.log("ALL ==>", I18n);
    at error (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:12819:16)
    at Module.traceVariable (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:13256:29)
    at ModuleScope.findVariable (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:11673:39)
    at Identifier.bind (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:7249:40)
    at CallExpression.bind (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:4669:28)
    at CallExpression.bind (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:8892:15)
    at ExpressionStatement.bind (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:4673:23)
    at Program.bind (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:4669:28)
    at Module.bindReferences (file:///Users/mazenkhalifa/React/IPW/DBM/platform-2.0/ipw-lms/node_modules/rollup/dist/es/shared/node-entry.js:12815:18)
error Command failed with exit code 1.```

## How to reproduce

Just install vite bundler, install i18n-js and run: vite build

## What do you expect

It should build successfully.

## What happened instead

It doesn't build. And fails with an fatal error.

## Software:

- node: 18.19.0
- yarn: 1.22.17
- I18n-js: latest

**Comment by fnando** [comment]
@mkhalifa013 can you please upload a sample app?

**Comment by fnando** [comment]
Just create a project and seems to be working as expected. Let me know if I'm missing something.

[vite-project.zip](https://github.com/fnando/i18n-js/files/14455161/vite-project.zip)
